### ISSUE TITLE
react-navigation support?

### ISSUE THREAD

**Issue by ConnyBr** [LinusU/expo-legacy-browser-support#1]
Hello Linus

I am trying to get expo build:web output javascript that is compatible with ie11. Problem starts when I add @react-navigation to my expo projekt.

app.js
`import React from 'react';
import { StatusBar } from 'expo-status-bar';
import { Text, Button } from 'react-native';
import StyleSheet from 'react-native-web/dist/exports/StyleSheet';
import View from 'react-native-web/dist/exports/View';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

export const Screen1 = ({ navigation }) => (
  <View style={styles.container}>
    <Text>Screen 1</Text>
    <Button title="Go to Screen 2" onPress={() => navigation.push('Screen2')} />
    <StatusBar style="auto" />
  </View>
);

export const Screen2 = () => (
  <View style={styles.container}>
    <Text>Screen 2</Text>
    <StatusBar style="auto" />
  </View>
);

const Stack = createStackNavigator();
export const AppStack = () => (
  <Stack.Navigator>
    <Stack.Screen name="Screen1" component={Screen1} />
    <Stack.Screen name="Screen2" component={Screen2} />
  </Stack.Navigator>
);

const SignIn = () => (
  <View style={styles.container}>
    <Text>Sign In</Text>
    <StatusBar style="auto" />
  </View>
);

const AuthStack = () => (
  <Stack.Navigator>
    <Stack.Screen name="SignIn" component={SignIn} />
  </Stack.Navigator>
);

export default ({ isLoggedIn = true }) => (
  <NavigationContainer>
    {isLoggedIn ? <AppStack /> : <AuthStack />}
  </NavigationContainer>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`

Ps. Installing expo-legacy-browser-support I must use --force flag on Expo 43.0.3? Right? Wrong? I also had to add these lines to babel.config.js to hide warnings:

module.exports = function(api) {
  api.cache(true);
  return {
    plugins: [
      ["@babel/plugin-proposal-class-properties", {loose: true}],
      ["@babel/plugin-proposal-private-methods", {loose: true}],
      ["@babel/plugin-proposal-private-property-in-object", {loose: true}]
    ],
    presets: ['expo-legacy-browser-support/babel'],
  };
};

Maybe I am doing something wrong or other config needs to be done to make that package work?

Thanks
/Conny

**Comment by LinusU** [comment]
Hello,

Sorry for the very late reply on this. I haven't had time to update this package to later versions of the Expo SDK.

We are using it with react-navigation so that _should_ work.

What is the exact error that you get when adding react-navigation?

**Comment by LinusU** [comment]
Could you please try with the new versions:

- For SDK 45: 2.0.0
- For SDK 46/47: 3.1.0
